### ISSUE TITLE
Tasks list

### ISSUE THREAD

**Issue by borparo** [koko-9898/C-2ConsoleGameProject#4]
Hello team, 
Yesterday Konstantin shared his code on Mario. And as Sasho suggested in a previous post, we can use issues to post  possible tasks and who is working on what.

As far as i know this is a list of how things are:
- [x] **Mario** - Kons
- [x] **Particle** - Kons
- [x] **Program** - Kons
- [x] **Levels** - Kristian? Vasil?
- [x] **Menus** - Ivelina
- [x] **Enemy** - Borja
- [x] **Scoring** -
- [ ] **Collision** -
- [x] **Hi Score Table** -
- [x] **Sounds** - Elena

__ feel free to review, update, the current list__

**Comment by koko-9898** [comment]
i am starting levels...

**Comment by vassildinev** [comment]
I'm doing loading levels from text files, so when the actual levels are complete we'll just merge the result.
